const SELECTORS = {
  buttons: {
    acceptAllButton: "[data-testid='uc-accept-all-button']",
    birthdayContinueButton: 'birthday-continue',
    childrenNoKidsContinue: 'children-no-kids-continue',
    childrenWithKidsContinueButton: 'children-with-kids-continue',
    employmentContinueButton: 'employment-status-continue',
    insuranceContinueButton: 'insurance-product-continue',
    insuranceStatusContinueButton: 'insurance-status-continue',
    resultContinueWithSignup: 'result-continue-with-signup',
    tariffOptionsRecommendedContinue: 'tariff-options-recommended-continue',
    tariffSelectButton: '[data-cy="tariff-select-button"]',
  },
  dailySicknessAllowanceInput: 'dsa-requested-payout-select',
  dayInput: 'day',
  employmentStatusOptionEmployed: 'employment-status-option-employed',
  fullInsurance: 'full-insurance',
  ingressDateSelect: 'ingress-date',
  incomeInput: 'income-input',
  insuranceStatusStatutory: 'insurance-status-statutory',
  insuranceTypeLabel: 'label',
  insureChildrenButton: 'insure-children-button',
  invalidAgeValidationMessage: 'invalid-age-validation-message',
  monthInput: 'month',
  negativeAgeValidationMessage: 'negative-age-validation-message',
  noChildrenButton: 'no-children-button',
  tariffTitle: 'tariff-title',
  yearInput: 'year',
};

export default SELECTORS;
