name: Self-Healing E2E Tests

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  test_and_heal:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Run Cypress tests
        id: cypress-run
        run: npm run cy:run
        continue-on-error: true
      - name: Upload reports artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: ./reports
          if-no-files-found: warn
      - name: Analyze test failures with AI
        if: steps.cypress-run.outcome == 'failure'
        run: npm run llm:analyze-failures
      - name: Create PR with fixes
        if: steps.cypress-run.outcome == 'failure'
        run: npm run llm:create-pr
